name: Build

on:
  - workflow_dispatch
  - workflow_call

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
      - run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: gw2-executable-loader
          path: |
            target/x86_64-pc-windows-msvc/release/gw2-executable-loader.dll
            target/x86_64-pc-windows-msvc/release/gw2-executable-loader.pdb
